"""initial schema

Revision ID: b53fcb51854d
Revises: 
Create Date: 2026-09-14 08:20:52.206437

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from foa.storage.models import UTCDateTime

revision: str = 'b53fcb51854d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.LargeBinary(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('owner_ref', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('concurrent_requests', sa.Integer(), nullable=False),
    sa.Column('tokens_per_day', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', UTCDateTime(), nullable=True),
    sa.Column('rotates_from', sa.String(length=64), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('last_used_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key_id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('permanent', sa.Boolean(), nullable=False),
    sa.Column('expires_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('lifted_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.create_index('ix_blacklist_active', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blacklist_node_id'), ['node_id'], unique=False)

    op.create_table('candidates',
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('observed_at', UTCDateTime(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('dns_names', sa.JSON(), nullable=False),
    sa.Column('asn', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('service_hint', sa.String(length=48), nullable=False),
    sa.Column('banner_hash', sa.String(length=128), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_ref', sa.JSON(), nullable=False),
    sa.Column('enrolled_node_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('expires_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('ip', 'port', 'protocol', name='uq_candidate_dedup')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index('ix_candidates_observed', ['observed_at'], unique=False)
        batch_op.create_index('ix_candidates_status', ['status'], unique=False)

    op.create_table('owners',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('public_key_type', sa.String(length=32), nullable=False),
    sa.Column('consent_method', sa.String(length=32), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('nodes',
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('scheme', sa.String(length=8), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('consent_id', sa.String(length=64), nullable=True),
    sa.Column('declared_models', sa.JSON(), nullable=False),
    sa.Column('observed_models', sa.JSON(), nullable=False),
    sa.Column('allowed_models', sa.JSON(), nullable=False),
    sa.Column('ollama_version', sa.String(length=64), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('max_requests_per_hour', sa.Integer(), nullable=False),
    sa.Column('max_tokens_per_hour', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('effective_weight', sa.Integer(), nullable=False),
    sa.Column('ewma_latency_ms', sa.Float(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('functional_check_enabled', sa.Boolean(), nullable=False),
    sa.Column('functional_check_model', sa.String(length=160), nullable=False),
    sa.Column('tls_required', sa.Boolean(), nullable=False),
    sa.Column('challenge_token', sa.String(length=128), nullable=False),
    sa.Column('challenge_expires_at', UTCDateTime(), nullable=True),
    sa.Column('last_health_check', UTCDateTime(), nullable=True),
    sa.Column('last_consent_check', UTCDateTime(), nullable=True),
    sa.Column('liveness_failures', sa.Integer(), nullable=False),
    sa.Column('readiness_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.PrimaryKeyConstraint('node_id'),
    sa.UniqueConstraint('endpoint', name='uq_nodes_endpoint')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_consent_id'), ['consent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_nodes_status', ['status'], unique=False)

    op.create_table('consents',
    sa.Column('consent_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('issued_at', UTCDateTime(), nullable=True),
    sa.Column('expires_at', UTCDateTime(), nullable=True),
    sa.Column('allowed_models', sa.JSON(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('max_requests_per_hour', sa.Integer(), nullable=False),
    sa.Column('data_policy', sa.JSON(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('challenge_token', sa.String(length=128), nullable=False),
    sa.Column('proof_snapshot', sa.JSON(), nullable=False),
    sa.Column('revoked_at', UTCDateTime(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.PrimaryKeyConstraint('consent_id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_consents_status', ['status'], unique=False)

    op.create_table('consent_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consent_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.consent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_history_consent_id'), ['consent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_history_consent_id'))

    op.drop_table('consent_history')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index('ix_consents_status')
        batch_op.drop_index(batch_op.f('ix_consents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_consents_node_id'))

    op.drop_table('consents')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_nodes_status')
        batch_op.drop_index(batch_op.f('ix_nodes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_nodes_consent_id'))

    op.drop_table('nodes')
    op.drop_table('owners')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_candidates_status')
        batch_op.drop_index('ix_candidates_observed')

    op.drop_table('candidates')
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklist_node_id'))
        batch_op.drop_index('ix_blacklist_active')

    op.drop_table('blacklist')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_subject')
        batch_op.drop_index('ix_audit_created')

    op.drop_table('audit_log')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
